apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: extra-worker-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - create
  - patch
  - update
  - delete
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: worker-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: extra-worker-role
subjects:
- kind: ServiceAccount
  name: argocd-terraform-worker
  namespace: argocd